### ISSUE TITLE
yocto_api.js - Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by driesdl** [yoctopuce/yoctolib_es2017#2]
This following error occurs on this line of code: **var dotpos = hwid.indexOf('.');**

`line 2513 /** Update device cache and YAPI function lists from yp records
     *
     * @param obj_ypRecs {Object}
     */

    imm_updateFromYP(obj_ypRecs)
    {
        var funidx = 0;
        for(var categ in obj_ypRecs) {
            for(var key in obj_ypRecs[categ]) {
                var rec = obj_ypRecs[categ][key];
                var hwid = rec['hardwareId'];
                var dotpos = hwid.indexOf('.');
                if(hwid.substr(0,dotpos) == this._serialNumber) {
                    var funydx = rec['index'];
                    if(funydx == undefined) funydx = funidx;
                    this._functions[funydx] = [hwid.substr(dotpos+1), rec['logicalName']];
                    funidx++;
                }
            }
        }
    }`

It runs over the Network category, but it also runs over the key `_super` and because of that, it throws this error. Shouldn't it just run over the elements in the array and not on keys?

If I manually change the code, it fails somewhere else in the code. It keeps on going. What could be the problem here?

**Comment by yoctopuce** [comment]
On which web browser do you get this error?

**Comment by driesdl** [comment]
Chromium Version 72.0.3626.81 - 64 bit - Windows 10
Same error occurs in latest Chrome version: Versie 76.0.3809.100

**Comment by yoctopuce** [comment]
I understand the cause of the error, but I have not been able to actually see it in order to make sure it is fixed. Can you provide the exact description of a scenario that makes this error appear ?

**Comment by driesdl** [comment]
Okay. We're building an interactive webapp, so we use the es2017 lib (files: yocto_api.js and yocto_genericsensor.js). We launch the Windows VirtualHub (VirtualHub.windows.35983). Connected to the YoctoPuce is a sensor, a Wire Draw Encoder (BCG13-K1KM05PP). We did a similair project in 2017, no problems back then. I tried with the same lib from 2017, but the error still occurs.

![image](https://user-images.githubusercontent.com/2621477/63337517-6669a180-c341-11e9-9bcf-9b38dca07f84.png)

In our code we try to connect to the Hub and Sensor with the following code:

```
async setupYoctoSensor() {
        const SENSOR_API = {
            host: "127.0.0.1",
            port: "4444",
            serial: "RX420MA1-1072A2"
        };
```

        await YAPI.LogUnhandledPromiseRejections();
        await YAPI.DisableExceptions();
        //
        let errorMessage = new YErrorMsg();

        await YAPI.RegisterHub(SENSOR_API.host + ':' + SENSOR_API.port, errorMessage);

        _module = YModule.FindModule(SENSOR_API.serial);
        _genericSensor = YGenericSensor.FindGenericSensor(SENSOR_API.serial + ".genericSensor1");

        await _genericSensor.registerValueCallback(this.fetchSensorValue);
    },

    async fetchSensorValue() {
        console.log("fetchSensorValue");
        console.log(await _genericSensor.get_currentValue());
    }

It fails on with the error message above.

`await YAPI.RegisterHub(SENSOR_API.host + ':' + SENSOR_API.port, errorMessage);`

![image](https://user-images.githubusercontent.com/2621477/63337931-26ef8500-c342-11e9-903e-695838395fa4.png)

This is the data right before the error:

![image](https://user-images.githubusercontent.com/2621477/63338320-dcbad380-c342-11e9-9318-19024bc27bc7.png)


Hit me up if you need more info!

**Comment by yoctopuce** [comment]
OK, your screenshot shows the root cause of the issue and the reason I was not seeing it.
You are using ember.js, and ember.js is actually modifying the Array class in a way which breaks compatibility with third-party library like ours. There has been a whole discussion about if these changes are conform to the standard or no (see https://github.com/emberjs/ember.js/issues/553 for instance), but the problem remains.
In order to make our lib work out of the box with ember.js, we should add a check for hasOwnProperty() in each for loop of our library, which is a pain but doable.

In between, you could disable the ember.js prototype extension if you don't really need them, as described in the issue above, by adding the following code BEFORE ember.js loads:
ENV = {};
ENV['EXTEND_PROTOTYPES'] = false;

**Comment by driesdl** [comment]
We indeed use Ember. I'll check it out and report back. Thanks for the help.

**Comment by driesdl** [comment]
@yoctopuce The problem is resolved when I added the prototype extension. Only had to change a arr.pushObject() code line.

**Comment by driesdl** [comment]
Different solution without having to change the EXTEND_PROTOTYPE value.


```
// Somewhere in your app.js file

// By default `Array.prototype._super` is enumerable which causes conflicts with your library.
// We can force it to be non-enumerable so everything works as expected.
// This code can be removed once the bug is fixed and released, or if we disable the prototype extensions in the app.
// More information: https://github.com/emberjs/ember.js/issues/19289

Object.defineProperty(Array.prototype, '_super', {
   enumerable: false,
});
```
